### ISSUE TITLE
These should be links to eventuate content - no Spring

### ISSUE THREAD

**Issue by cer** [eventuate-tram/start.eventuate.io#8]
![image](https://user-images.githubusercontent.com/246234/79798584-1434b200-830e-11ea-825d-aece42404c3f.png)

@dartartem

**Comment by dartartem** [comment]
Could you please specify proper references?

**Comment by cer** [comment]
https://github.com/eventuate-tram
https://twitter.com/eventuateio
Hide the help menu?
